import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { UserDataProvider } from "./context/UserData";
import { RepoProvider } from './context/RepoData';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Github Finder',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <UserDataProvider>
        <RepoProvider>
          <body className={inter.className}>
              {children}
          </body>
        </RepoProvider>
      </UserDataProvider>
    </html>
  )
}
