import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { UserDataProvider } from "./context/UserData";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Github Finder',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <UserDataProvider>
        <body className={inter.className}>
            {children}
        </body>
      </UserDataProvider>
    </html>
  )
}
